CREATE DATABASE JAV_PROCESOS_FINAL_DB;
USE JAV_PROCESOS_FINAL_DB;

CREATE TABLE GENDER_TYPE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(15) NOT NULL
);

CREATE TABLE IDENTIFICATION_TYPE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(15) NOT NULL
);

CREATE TABLE PHONE_TYPE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(15) NOT NULL
);

CREATE TABLE PRODUCT_TYPE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION VARCHAR(15) NOT NULL
);

CREATE TABLE CLIENT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	IDENTIFICATION_NUMBER VARCHAR(15) NOT NULL,
	IDENTIFICATION_TYPE INT NOT NULL,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	GENDER_TYPE INT NOT NULL,
	EMAIL VARCHAR(55) NOT NULL,
	DATE_BIRTH TIMESTAMP NOT NULL,
	CONSTRAINT fk_gender FOREIGN KEY(GENDER_TYPE)
      REFERENCES JAV_PROCESOS_FINAL_DB.GENDER_TYPE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_identification_type FOREIGN KEY(IDENTIFICATION_TYPE)
      REFERENCES JAV_PROCESOS_FINAL_DB.IDENTIFICATION_TYPE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    UNIQUE KEY(IDENTIFICATION_NUMBER,IDENTIFICATION_TYPE)
);

CREATE TABLE CLIENT_CONTACT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CLIENT INT NOT NULL,
	PHONE_TYPE INT NOT NULL,
	PHONE VARCHAR(25) NOT NULL,
	CONSTRAINT fk_client FOREIGN KEY(CLIENT)
      REFERENCES JAV_PROCESOS_FINAL_DB.CLIENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT fk_phone FOREIGN KEY(PHONE_TYPE)
      REFERENCES JAV_PROCESOS_FINAL_DB.PHONE_TYPE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE PRODUCT_REQUEST (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CLIENT INT NOT NULL,
	PRODUCT_TYPE INT NOT NULL,
	IS_ACCEPTED BOOL NOT NULL,
	CONSTRAINT fk_prod_req_client FOREIGN KEY(CLIENT)
      REFERENCES JAV_PROCESOS_FINAL_DB.CLIENT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT fk_product_req_type FOREIGN KEY(PRODUCT_TYPE)
      REFERENCES JAV_PROCESOS_FINAL_DB.PRODUCT_TYPE (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT_REQUEST INT NOT NULL,
	ACCOUNT_NUMBER VARCHAR(25) NOT NULL,
	BALANCE DOUBLE NOT NULL,
	CONSTRAINT fk_product_request FOREIGN KEY(PRODUCT_REQUEST)
      REFERENCES JAV_PROCESOS_FINAL_DB.PRODUCT_REQUEST (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    UNIQUE KEY(PRODUCT_REQUEST)
);

CREATE TABLE CDT_PRODUCT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	PRODUCT INT NOT NULL,
	TERM INT NOT NULL,
	RATE DOUBLE NOT NULL,
	CONSTRAINT fk_product FOREIGN KEY(PRODUCT)
      REFERENCES JAV_PROCESOS_FINAL_DB.PRODUCT (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

INSERT INTO GENDER_TYPE (DESCRIPTION)  VALUES ('MASCULINO'),('FEMENINO');
INSERT INTO IDENTIFICATION_TYPE (DESCRIPTION)  VALUES ('C.C.'),('C.E.');
INSERT INTO PHONE_TYPE (DESCRIPTION) VALUES ('CELULAR'), ('FIJO');
INSERT INTO PRODUCT_TYPE (DESCRIPTION) VALUES ('CUENTA AHORRO'), ('CDT');
INSERT INTO CLIENT (IDENTIFICATION_NUMBER, IDENTIFICATION_TYPE, FIRST_NAME, LAST_NAME, GENDER_TYPE, EMAIL, DATE_BIRTH) VALUES 
	('10101010', 1, 'LEELA', 'TURANGA', 2, 'LEEALA@FUTURAMA.COM', '1990-01-01 00:00:00'),
	('20202020', 2, 'HOMERO', 'SIMPSON', 1, 'HOMERO@SIMPSON.COM', '1991-01-01 00:00:00'),
	('30303030', 1, 'LIGTH', 'YAGAMI', 1, 'LIGTH@DEATHNOTE.COM', '1992-01-01 00:00:00');
INSERT INTO CLIENT_CONTACT (CLIENT, PHONE_TYPE, PHONE) VALUES 
	(1, 1, '3129292922'),
	(1, 2, '7347263'),
	(2, 1, '3129292923'),
	(3, 1, '3129292924');
INSERT INTO PRODUCT_REQUEST (CLIENT, PRODUCT_TYPE, IS_ACCEPTED) VALUES 
	(1, 1, TRUE),
	(1, 2, TRUE),
	(2, 1, TRUE),
	(3, 1, TRUE);
INSERT INTO PRODUCT (PRODUCT_REQUEST, ACCOUNT_NUMBER, BALANCE) VALUES 
	(1, '0000001', 1000000),
	(2, '0000002', 3000000),
	(3, '0000003', 9000000),
	(4, '0000004', 8500000);
INSERT INTO CDT_PRODUCT (PRODUCT, TERM, RATE) VALUES 
	(2, 39, 3.00);


DROP DATABASE JAV_PROCESOS_FINAL_DB;

